### PR TITLE
Unit tests - Initial setup and first few classes of tests

### PR DESCRIPTION
**Pull request by AshRolls**
Could somebody take a look at this first set of unit tests please? I have simply chosen the first class from /core directory and started testing. You will find a new project in the solution, and we are using the Visual Studio built in unit test functionality, and the Test Explorer.

Specific feedback in particular is welcome on:

1. General approach / structure of tests
2. Any project specific settings that may be missing or wrong (.NET version for example)
3. Tests that are missing or incomplete

* Please note I am aware that we are not using proper isolation / dependency injection / mocking techniques in these tests. To do that would require larger reworks of the base code which is a change for a later date in discussion with Erik Zhang, at the moment we are just aiming to get some basic coverage going.

After incorporating any feedback received I will be able to start moving through each class in turn adding tests, but we really want to get our initial approach right to save wasting effort further down the line.

### CODE REVIEW

**Comment by canesin** [comment]
Greate work @AshRolls, my comment is that after review you should add to the readme.md correspondent documentation on how to run the testing suit.

To settle form I will escalate now and ping @erikzhang to take a look on this.. Erik this touch core code could you please take a look at Ash work and comment.

**Comment by AshRolls** [comment]
The root readme.md is in chinese so I can't add to that. For the moment I will create a new, english, readme.md within the `src/AntShares.UnitTest/` sub directory.

**Comment by erikzhang** [comment]
It seems all changes to the core code has been removed?

**Comment by AshRolls** [comment]
Yes, the unit test project is completely stand-alone for the moment. Earlier commits on this branch included some experiments with using SimpleInjector and interfacing to the core code, but I am not using this at the moment so have removed it until it's needed.

**Comment by erikzhang** [comment]
That should be fine.

**Comment by AshRolls** [comment]
@lucianoengel did you have a chance to run these tests so this can get merged in?

**Comment by canesin** [comment]
@AshRolls did you test in linux ? If so, I believe we are ready to PR to a branch in AntShares master for more people to collaborate on and so that we can setup a CI workflow.

**Comment by AshRolls** [comment]
@canesin No, I have no linux environment setup to test in. I have added to the readme with information about how the tests can be run from the command line, which should work from linux, but this will need verifying by someone linux flavoured.

**Comment by canesin** [comment]
image
@AshRolls will wait for the addition of "dotnet restore" inside the folder and you can merge

**Pull request merged**
